### ISSUE TITLE
BUG multiple calendars currently do not populate from Google if added in CMS

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-google-calendar#2]

**Comment by muskie9-opensource** [comment]
Multi-calendar functionality works as expected. Documentation on troubleshooting will help with this. The underlying issue was `Make available to public` not being checked in the calendar settings within Google.

<img width="669" alt="Screenshot 2022-09-25 at 3 08 57 PM" src="https://user-images.githubusercontent.com/113001544/192163172-f4209a65-2d45-4363-9343-199b996fb35f.png">
